version: '3.9'
services:
  api:
    image: "centraliot.azurecr.io/devices-api:latest"
    environment:
      - TZ=America/Bahia
  - ConnectionStrings__Devices=Server=mysql;Database=SmartHome-Devices;User ID=smarthomeiot;Password=ma522770;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=30;Connection LifeTime=600;Default Command Timeout=15;Connection Timeout=5;Connection Reset=true;
      - Logging__LogLevel__Default=Error
      - Logging__LogLevel__Microsoft=Error
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Error
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 100
      resources:
        limits:
          cpus: '1'
          memory: 200M
        reservations:
          cpus: '0'
          memory: 20M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.devices.rule=PathPrefix(`/devices`)"
        - "traefik.http.routers.devices.entrypoints=web"
        - "traefik.http.services.devices.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.devices-strip.stripPrefix.prefixes=/devices"
        - "traefik.http.routers.devices.middlewares=global-sec@file,devices-strip@swarm"
        - "traefik.http.routers.devices-ip.rule=PathPrefix(`/devices`)"
        - "traefik.http.routers.devices-ip.entrypoints=web"
        - "traefik.http.routers.devices-ip.service=devices"
        - "traefik.http.routers.devices-ip.middlewares=global-sec@file,devices-strip@swarm"
        - "traefik.docker.network=overlay-swarm"

networks:
  default:
    external: true
    name: overlay-swarm