version: '3.9'
services:
  api:
    image: "centraliot.azurecr.io/devices-api:latest"
    environment:
      - TZ=America/Bahia
      - ConnectionStrings__Devices=Server=mysql;Database=SmartHome-Devices;User ID=smarthomeiot;Password=ma522770;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;Connection Idle Timeout=120;Connection Lifetime=1800;Keepalive=15;Default Command Timeout=15;Connection Timeout=5;UseCompression=true;AllowLoadLocalInfile=false
      - Logging__LogLevel__Default=Error
      - Logging__LogLevel__Microsoft=Error
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Error
      # OpenTelemetry (Grafana): usar as variáveis padrão OTEL_*
      - OTEL_RESOURCE_ATTRIBUTES="service.name=SmartHome-Api,service.namespace=iot-smart-home,deployment.environment=production"
      - OTEL_EXPORTER_OTLP_ENDPOINT="https://otlp-gateway-prod-sa-east-1.grafana.net/otlp"
      - OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic MTM5NTM3MTpnbGNfZXlKdklqb2lNVFUxTVRNeE55SXNJbTRpT2lKaGNHa3RjMjFoY25Sb2IyMWxJaXdpYXlJNkltWXdaamhvZW5oTE4zRjZPVE01ZFhSRE5YUnROblEzTWlJc0ltMGlPbnNpY2lJNkluQnliMlF0YzJFdFpXRnpkQzB4SW4xOQ=="
      - OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
      - OTEL_TRACES_SAMPLER=parentbased_always_on
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 100
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0'
          memory: 20M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.devices.rule=PathPrefix(`/devices`)"
        - "traefik.http.routers.devices.entrypoints=web"
        - "traefik.http.services.devices.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.devices-strip.stripPrefix.prefixes=/devices"
        - "traefik.http.routers.devices.middlewares=global-sec@file,devices-strip@swarm"
        - "traefik.http.routers.devices-ip.rule=PathPrefix(`/devices`)"
        - "traefik.http.routers.devices-ip.entrypoints=web"
        - "traefik.http.routers.devices-ip.service=devices"
        - "traefik.http.routers.devices-ip.middlewares=global-sec@file,devices-strip@swarm"
        - "traefik.docker.network=overlay-swarm"

networks:
  default:
    external: true
    name: overlay-swarm