# @SmartHome_Api_HostAddress = http://iotserver.local:8081/api/v1
@SmartHome_Api_HostAddress = http://localhost:8081/api/v1

GET {{SmartHome_Api_HostAddress}}/devices/
Accept: application/json

###
